Repository multiverseweb/Dataverse, pull requests merged in 2024-10, with the labels that each got.

#9 now different tabs open
  index.html
Labels: Further Improvement Required

#18 solved #14
  index.html
  website/script.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#22 gssoc-HarishBoopathi
  website/script.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1, Further Improvement Required

#24 Added All Contributors' Profile Photos
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#41 Support Plotting RadarChart - issue #3
  software/mainGUI.py
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level3

#46 Add Automated Greeting Workflow
  .github/workflow/greetings.yml
Labels: hacktoberfest-accepted, gssoc-ext, level2

#50 Fixed contact page #49
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#59 ✨ Enhance Logo Scroll Feature in "Here are some examples of what you can do with Dataverse" Section #56
  index.html
  website/script.js
Labels: hacktoberfest-accepted, gssoc-ext, level2

#61 Support Plotting 3D Scatter Plot issue #7
  software/mainGUI.py
Labels: hacktoberfest-accepted, gssoc-ext, level3

#62 Added and styled Code of Conduct and License Page on website
  index.html
  website/codeOfconduct.html
  website/codeOfconduct.js
  website/license.html
  website/license.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#63 Revert "now different tabs open"
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#65 done
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#68 Footer update
  index.html
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#87 link to home page is included in the navbar of license.html and codeO…
  index.html
  website/codeOfconduct.html
  website/license.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#92 Issue #89
  index.html
  website/script.js
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#96 improve preloader
  index.html
  website/script.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level3

#106 Made changes to the footer section for copyright section of the license page
  index.html
  styles.css
  website/license.html
  website/license.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#104 solved issue #98
  index.html
  login.html
  signup.html
Labels: hacktoberfest-accepted, gssoc-ext, level3

#118 I have fixed the glow on the light and dark mode buttons, it now selects the right theme
  .vscode/settings.json
  index.html
  styles.css
  website/codeOfconduct.html
  website/codeOfconduct.js
  website/license.html
  website/license.js
  website/script.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#129 Update README.md
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#134 Update index.html
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#138 Make the copyright year dynamic in the LICENSE section. #74
  index.html
  website/license.html
  website/license.js
  website/script.js
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1, Further Improvement Required

#124 The navbar font size is increased, and the license section font style and its font properties have been changed to increase the readability.
  index.html
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#143 Adding the contributors page to mention all the awersome people who have contributed to the website.
  index.html
  website/contributor.css
  website/contributor.html
  website/contributor.js
  website/script.js
Labels: hacktoberfest-accepted, gssoc-ext, level3

#130 Scroll up #120
  index.html
  website/script.js
  website/style.css
  website/web_images/arrow-up.png
  website/web_images/arrow.png
Labels: hacktoberfest-accepted, gssoc-ext, level2

#157 Revert "Scroll up #120"
  index.html
  website/script.js
  website/style.css
  website/web_images/arrow-up.png
  website/web_images/arrow.png
Labels: bug, hacktoberfest-accepted, gssoc-ext

#146 solved issue #100
  index.html
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#159 Update codeOfconduct.html
  website/codeOfconduct.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#161 Update license.html
  website/license.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#175 Form and Input Field Hover Effects Enhancement
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#176 Update contributor.html
  website/contributor.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#139 Trusted_email_services_for_signup
  signup.html
Labels: hacktoberfest-accepted, gssoc-ext, level3

#189 Fixed pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#125 Add images to button issue #51
  software/images/area_chart.png
  software/images/bar_graph.png
  software/images/heatmap_plot.png
  software/images/histogram.png
  software/images/line_graph.png
  software/images/pie_chart.png
  software/images/radar_chart.png
  software/images/scatter_plot.png
  software/mainGUI.py
Labels: hacktoberfest-accepted, gssoc-ext, level3, Further Improvement Required

#207 Fixed Set upper limit to 16 #issue 198
  software/mainGUI.py
Labels: hacktoberfest-accepted, gssoc-ext, level3

#116 Enhance PDF Report with Detailed Financial Summary and Dynamic Plot Inclusion #114
  AliceBrown-2024-10-15-Dataverse.pdf
  John Doe-2024-10-11.pdf
  combined_plot.png
  software/__pycache__/report.cpython-311.pyc
  software/database.sql
  software/report.py
  software/tempCodeRunnerFile.py
Labels: hacktoberfest-accepted, gssoc-ext, level3, Further Improvement Required

#214 changed the footer link to bright color
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#215 footer text visibility
  index.html
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#220 Successfully updated code_of_conduct.md
  code_of_conduct.md
Labels: hacktoberfest-accepted, gssoc-ext, level2

#229 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#234 authentication button appears now across all pages
  index.html
  website/style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#216 Github actions for more connectivity!
  .github/workflows/issue_open_close.yml
  .github/workflows/pr_merge.yaml
  .github/workflows/pr_raise.yml
Labels: hacktoberfest-accepted, gssoc-ext, level2

#221 Added github issue labeler workflow
  .github/workflows/issue_labeler.yaml
Labels: hacktoberfest-accepted, gssoc-ext, level2

#246 Revert "Added github issue labeler workflow"
  .github/workflows/issue_labeler.yaml
Labels: hacktoberfest-accepted, gssoc-ext, level3

#183 Done some enhancements and also added some new sections
  Contributing.md
Labels: hacktoberfest-accepted, gssoc-ext, level3, Further Improvement Required

#260 Changed login and signup pages to incorporate 3rd party authentication
  website/login.html
  website/signup.html
Labels: hacktoberfest-accepted, gssoc-ext, level3

#258 Bug in GUI #issue 53
  software/main.py
Labels: hacktoberfest-accepted, gssoc-ext, level3

#111 Update financeTracker.py
  software/financeTracker.py
Labels: hacktoberfest-accepted, gssoc-ext, level3

#262 Implement Issue Reminder Workflow🚀
  .github/workflows/issue-reminder.yml
Labels: hacktoberfest-accepted, gssoc-ext, level2
