Repository multiverseweb/Dataverse, pull requests merged in 2024-11, with the labels that each got.

#259 Enhance UI and Add New Functionalities for Interactive Map and Theme …
  website/script.js
Labels: hacktoberfest-accepted, gssoc-ext, level3

#272 Revert "Enhance UI and Add New Functionalities for Interactive Map and Theme …"
  website/script.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#280 Added "remember me" to the signup and signin page connecting it to the local storage database for user authentication.
  website/login.html
  website/signup.html
Labels: hacktoberfest-accepted, gssoc-ext, level2

#292 README.md path update (variant2)
  index.html
  website/pages/codeOfconduct.html
  website/pages/license.html
  website/scripts/script.js
Labels: gssoc-ext, level1

#307 Created a new PR for the addition of star rating to the feedback section.
  index.html
  website/styles/style.css
Labels: gssoc-ext, level2

#312 Fixed the unintended behaviour of the hover effect on the links.
  website/styles/style.css
Labels: good first issue, gssoc-ext, level1

#313 Automation of project structure updation using GitHub workflows and Python scripts
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  Documentation/PROJECT_STRUCTURE.md
  Documentation/repo_structure.txt
  README.md
Labels: gssoc-ext, level3

#317 Indicator positioning fix V2.
  website/styles/style.css
Labels: gssoc-ext, level2

#319 Undone the accidental deletion of the previous hover effect fix.
  website/styles/style.css
Labels: gssoc-ext

#315 Added the ability to toggle between view/hide password in the signup …
  website/pages/login.html
  website/pages/signup.html
  website/web_images/hide_password_icon.png
  website/web_images/view_password_icon.png
Labels: gssoc-ext, level3

#320 Final commit (V2).
  website/pages/login.html
  website/pages/signup.html
Labels: gssoc-ext

#308 Display version in software #issue 305
  software/main.py
Labels: gssoc-ext, level2

#322 Contributions value fix
  website/scripts/contributor.js
Labels: gssoc-ext, level1

#323 Show popup/modal after feedback submit.
  index.html
  website/scripts/script.js
  website/styles/style.css
Labels: gssoc-ext, level2

#328 Contributors , Total Contributions value showing wrong
  website/scripts/contributor.js
Labels: gssoc-ext, level2

#327 Fixed wrong link paths.
  Documentation/Contributing.md
  index.html
Labels: gssoc-ext, level1

#340 Fix download button.
  website/styles/style.css
Labels: Further Improvement Required
