Repository multiverseweb/Dataverse, pull requests merged in 2025-01, with the labels that each got.

#359 Docs/improve installation instructions
  README.md
  software/__pycache__/financeTracker.cpython-312.pyc
  software/manage_data.py
Labels: SWOC, INTERMEDIATE

#372 Update report.py
  software/report.py
Labels: SWOC, INTERMEDIATE

#380 Added tooltips in the contact form
  index.html
  website/styles/style.css
Labels: SWOC, INTERMEDIATE

#384 Update support.html- Added the "Go To Home" button.
  website/pages/support.html
Labels: SWOC, BEGINNER

#383 Implemented infinite scrolling on example images in index.html
  index.html
  website/styles/style.css
Labels: Further Improvement Required, SWOC, BEGINNER

#381 Added navbar in reviews.html
  website/pages/reviews.html
  website/styles/reviews.css
Labels: Further Improvement Required, SWOC, BEGINNER

#385 Update the "versions.html" page
  website/pages/versions.html
  website/styles/style.css
Labels: documentation, Further Improvement Required, SWOC, INTERMEDIATE
